language: ruby
install:
  - bundle install --path vendor/bundle
script:
  - bundle exec middleman build --clean

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: master
