language: ruby
install:
  - bundle install --path vendor/bundle
script:
  - bundle exec jekyll build

deploy:
  provider: pages
  target-branch: gh-pages
  github-token: $GH_REPO_PAULRBR_TOKEN
  skip-cleanup: true
  keep-history: true
  on:
    branch: master
